In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('database_tong.csv')
df.head()

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,...,valid_points,grid_log,Latitude,Longitude,Rainfall,Temp_Mean,Temp_Max,Temp_Min,Heat_Stress_Days,Year
0,177321,0.8510272331,Bagerhat,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,...,5,✅⚠️✅✅✅,22.655478,89.794181,1451.65,27.768699,33.57,18.56,0,2022
1,25646,1.175777899,Bandarban,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,...,5,✅✅✅✅✅,21.787476,92.412475,1354.97,26.048780,32.68,17.05,0,2022
2,231401,0.7705887183,Barguna,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,...,5,✅✅✅⚠️⚠️,22.131336,90.117243,1785.97,28.127317,32.51,20.84,0,2022
3,302665,0.7571043893,Barishal,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,...,5,⚠️⚠️✅✅✅,22.493403,90.354801,1601.92,27.991220,32.47,19.53,0,2022
4,388575,1.100652384,Bhola,Kharif 2,26.0,72.5,Aman,June,July to Oct,Nov to Dec,...,3,✅✅❌❌✅,22.143569,90.790409,2272.77,28.436423,31.57,21.83,0,2022

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4535 entries, 0 to 4534
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Area                   4535 non-null   int64
 1   AP Ratio               4535 non-null   str
 2   District               4535 non-null   str
 3   Season                 4535 non-null   str
 4   Avg Temp               4535 non-null   float64
 5   Avg Humidity           4535 non-null   float64
 6   Crop Name              4535 non-null   str
 7   Transplant             4535 non-null   str
 8   Growth                 4535 non-null   str
 9   Harvest                4535 non-null   str
 10  Production             4535 non-null   int64
 11  Max Temp               4535 non-null   int64
 12  Min Temp               4535 non-null   float64
 13  Max Relative Humidity  4535 non-null   int64
 14  Min Relative Humidity  4535 non-null   int64
 15  soil_ph                4535 non-null   float64
 16  NDVI_early             4535 non-null   float64
 17  NDVI_mid               4535 non-null   float64
 18  NDVI_late              4535 non-null   float64
 19  NDVI_std               4535 non-null   float64
 20  NDVI_prev_season       4535 non-null   float64
 21  EVI_Season             4535 non-null   float64
 22  LAI_Season             4535 non-null   float64
 23  FPAR_Season            4535 non-null   float64
 24  LST_Season             4535 non-null   float64
 25  Soil_Moisture_Season   4535 non-null   float64
 26  pH                     4535 non-null   float64
 27  Organic_Carbon         4535 non-null   float64
 28  Nitrogen               4535 non-null   float64
 29  Clay                   4535 non-null   float64
 30  Sand                   4535 non-null   float64
 31  Silt                   4535 non-null   float64
 32  Bulk_Density           4535 non-null   float64
 33  valid_points           4535 non-null   int64
 34  grid_log               4535 non-null   str
 35  Latitude               4535 non-null   float64
 36  Longitude              4535 non-null   float64
 37  Rainfall               4535 non-null   float64
 38  Temp_Mean              4535 non-null   float64
 39  Temp_Max               4535 non-null   float64
 40  Temp_Min               4535 non-null   float64
 41  Heat_Stress_Days       4535 non-null   int64
 42  Year                   4535 non-null   int64
dtypes: float64(27), int64(8), str(8)
memory usage: 1.5 MB

In [4]:
df.isnull().sum()

Area                     0
AP Ratio                 0
District                 0
Season                   0
Avg Temp                 0
Avg Humidity             0
Crop Name                0
Transplant               0
Growth                   0
Harvest                  0
Production               0
Max Temp                 0
Min Temp                 0
Max Relative Humidity    0
Min Relative Humidity    0
soil_ph                  0
NDVI_early               0
NDVI_mid                 0
NDVI_late                0
NDVI_std                 0
NDVI_prev_season         0
EVI_Season               0
LAI_Season               0
FPAR_Season              0
LST_Season               0
Soil_Moisture_Season     0
pH                       0
Organic_Carbon           0
Nitrogen                 0
Clay                     0
Sand                     0
Silt                     0
Bulk_Density             0
valid_points             0
grid_log                 0
Latitude                 0
Longitude                0
Rainfall                 0
Temp_Mean                0
Temp_Max                 0
Temp_Min                 0
Heat_Stress_Days         0
Year                     0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

-------Xóa các cột có giá trị trùng lặp nếu trống hơn 50 phần trăm cột -------

In [6]:
limit = len(df.columns) * 0.5
df_cleaned = df.dropna(thresh=limit)
df_cleaned = df_cleaned.drop_duplicates()

In [7]:
cols_to_drop=['Year', 'Latitude', 'Longitude', 'soil_ph']
existing_cols = [col for col in cols_to_drop if col in df.columns]
if existing_cols:
    # Xóa cột (axis=1 là xóa cột, inplace=True để áp dụng trực tiếp vào df)
    df.drop(columns=existing_cols, inplace=True)
    print(f"Đã xóa thành công các cột: {existing_cols}")
else:
    print("Không tìm thấy các cột cần xóa trong DataFrame.")

# Kiểm tra lại kết quả
print(f"Số lượng cột còn lại: {len(df.columns)}")

Đã xóa thành công các cột: ['Year', 'Latitude', 'Longitude', 'soil_ph']
Số lượng cột còn lại: 39

In [8]:

import seaborn as sns
import matplotlib.pyplot as plt

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=['object']).columns.tolist()

print(f"Các cột số: {len(num_cols)}")
print(f"Các cột phân loại: {len(cat_cols)}")

# 2. Kiểm tra độ tương quan và lọc bỏ biến trùng lặp (như đã phân tích)
corr_matrix = df[num_cols].corr()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)] # Ngưỡng khắt khe 0.95
df.drop(columns=to_drop, inplace=True)
print(f"Đã xóa các cột tương quan quá cao: {to_drop}")

# 3. Tính độ lệch (Skewness) - Đã sửa lỗi NameError
num_cols = df.select_dtypes(include=[np.number]).columns.tolist() # Cập nhật lại danh sách cột sau khi xóa
skewed_feats = df[num_cols].skew().sort_values(ascending=False)
print("\nTop 5 cột bị lệch (Skewed) nhất:")
print(skewed_feats.head(5))

Các cột số: 31
Các cột phân loại: 8
Đã xóa các cột tương quan quá cao: []

Top 5 cột bị lệch (Skewed) nhất:
Area                    8.299929
Production              7.809943
Soil_Moisture_Season    2.428967
LAI_Season              1.852854
Nitrogen                1.619616
dtype: float64

C:\Users\ASUS\AppData\Local\Temp\ipykernel_21736\1658187229.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include=['object']).columns.tolist()

Code xử lỹ chuẩn hóa cấu trúc

In [9]:
def structural_cleaning(df):
    # Tạo bản sao
    df_clean = df.copy()

    # 1. Nhất quán văn bản (Cực kỳ quan trọng cho District và Crop Name)
    # Loại bỏ khoảng trắng thừa ở đầu/cuối và đưa về chữ thường để tránh trùng lặp ẩn
    text_cols = ['District', 'Crop Name', 'Season', 'Growth', 'Harvest', 'Transplant']
    for col in text_cols:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.lower()
    
    # Ví dụ: Xử lý thủ công nếu bạn phát hiện lỗi đánh máy cụ thể
    # mapping = {'ha noi': 'hanoi', 'hcm city': 'ho chi minh'}
    # df_clean['District'] = df_clean['District'].replace(mapping)

    # 2. Định dạng kiểu dữ liệu
    # Ép kiểu các cột chỉ số thực vật và thời tiết về float64
    float_cols = ['Avg Temp', 'Avg Humidity', 'Rainfall', 'pH', 'Organic_Carbon', 'Nitrogen']
    # Tìm tất cả các cột NDVI, EVI, LAI, FPAR, LST để ép kiểu float
    ndvi_related = [c for c in df_clean.columns if any(x in c for x in ['NDVI', 'EVI', 'LAI', 'FPAR', 'LST'])]
    
    for col in float_cols + ndvi_related:
        if col in df_clean.columns:
            df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

    # Ép kiểu các cột định lượng lớn về int64
    int_cols = ['Production', 'Max Temp', 'Heat_Stress_Days']
    for col in int_cols:
        if col in df_clean.columns:
            # fillna(0) trước khi ép kiểu int vì cột chứa NaN không thể ép thành int
            df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce').fillna(0).astype('int64')

    # 3. Xóa bỏ các cột thừa (Redundant)
    # 'grid_log' thường là ID nội bộ của hệ thống thu thập, không có giá trị dự báo
    # 'valid_points' nếu giá trị giống nhau cho mọi dòng cũng nên xóa
    redundant_cols = ['grid_log', 'valid_points']
    df_clean.drop(columns=[c for c in redundant_cols if c in df_clean.columns], inplace=True)

    return df_clean

# Thực thi
df = structural_cleaning(df)
print("--- Cấu trúc sau khi dọn dẹp ---")
print(df.info())

--- Cấu trúc sau khi dọn dẹp ---
<class 'pandas.DataFrame'>
RangeIndex: 4535 entries, 0 to 4534
Data columns (total 37 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Area                   4535 non-null   int64
 1   AP Ratio               4535 non-null   str
 2   District               4535 non-null   str
 3   Season                 4535 non-null   str
 4   Avg Temp               4535 non-null   float64
 5   Avg Humidity           4535 non-null   float64
 6   Crop Name              4535 non-null   str
 7   Transplant             4535 non-null   str
 8   Growth                 4535 non-null   str
 9   Harvest                4535 non-null   str
 10  Production             4535 non-null   int64
 11  Max Temp               4535 non-null   int64
 12  Min Temp               4535 non-null   float64
 13  Max Relative Humidity  4535 non-null   int64
 14  Min Relative Humidity  4535 non-null   int64
 15  NDVI_early             4535 non-null   float64
 16  NDVI_mid               4535 non-null   float64
 17  NDVI_late              4535 non-null   float64
 18  NDVI_std               4535 non-null   float64
 19  NDVI_prev_season       4535 non-null   float64
 20  EVI_Season             4535 non-null   float64
 21  LAI_Season             4535 non-null   float64
 22  FPAR_Season            4535 non-null   float64
 23  LST_Season             4535 non-null   float64
 24  Soil_Moisture_Season   4535 non-null   float64
 25  pH                     4535 non-null   float64
 26  Organic_Carbon         4535 non-null   float64
 27  Nitrogen               4535 non-null   float64
 28  Clay                   4535 non-null   float64
 29  Sand                   4535 non-null   float64
 30  Silt                   4535 non-null   float64
 31  Bulk_Density           4535 non-null   float64
 32  Rainfall               4535 non-null   float64
 33  Temp_Mean              4535 non-null   float64
 34  Temp_Max               4535 non-null   float64
 35  Temp_Min               4535 non-null   float64
 36  Heat_Stress_Days       4535 non-null   int64
dtypes: float64(24), int64(6), str(7)
memory usage: 1.3 MB
None

Xử lý những giá trị năng xuất không hợp lệ = 0 hoặc vô lý

In [11]:

def clean_production_and_invalid(df):
    df_clean = df.copy()
    
    # 1. Chuyển đổi cột 'Production' sang số, ép các giá trị rác (chữ, ký tự lạ) thành NaN
    # errors='coerce' sẽ biến "không xác định" thành NaN
    df_clean['Production'] = pd.to_numeric(df_clean['Production'], errors='coerce')
    
    # 2. Xử lý giá trị 0
    # Trong Data Cleaning, ta coi 0 là giá trị không hợp lệ cho năng suất
    # Bạn có thể chọn biến 0 thành NaN để xóa đồng nhất ở bước sau
    df_clean['Production'] = df_clean['Production'].replace(0, np.nan)
    
    # 3. Xóa các dòng có Production là NaN (bao gồm: rác ban đầu, chữ ban đầu và số 0)
    initial_shape = df_clean.shape[0]
    df_clean = df_clean.dropna(subset=['Production'])
    
    print(f"Đã loại bỏ {initial_shape - df_clean.shape[0]} dòng có năng suất không hợp lệ (rác hoặc bằng 0).")
    
    # 4. Tự động tìm và xóa các cột có quá nhiều giá trị rác hoặc toàn 0
    # Nếu một cột có hơn 90% là 0 hoặc NaN, cột đó không có giá trị dự báo
    for col in df_clean.columns:
        if df_clean[col].isnull().mean() > 0.9 or (df_clean[col] == 0).mean() > 0.9:
            df_clean.drop(columns=[col], inplace=True)
            print(f"Đã xóa cột '{col}' do chứa quá nhiều dữ liệu rác/số 0.")
            
    return df_clean

# Thực thi
df = clean_production_and_invalid(df)

Đã loại bỏ 410 dòng có năng suất không hợp lệ (rác hoặc bằng 0).

In [12]:


def clean_features_only(df):
    df_clean = df.copy()
    
    # 1. Chỉ lọc Logic cho các biến môi trường (Bỏ qua Production)
    logic_conditions = (
        (df_clean['pH'].between(0, 14)) & 
        (df_clean['Avg Humidity'].between(0, 100)) &
        (df_clean['Rainfall'] >= 0)
    )
    
    # Lọc NDVI nếu có
    ndvi_cols = [c for c in df_clean.columns if 'NDVI' in c]
    for col in ndvi_cols:
        logic_conditions &= df_clean[col].between(-1, 1)
        
    df_clean = df_clean[logic_conditions]
    print(f"Đã dọn dẹp xong Logic cho các biến đầu vào. Giữ nguyên cột Production.")

    # 2. Xử lý Outliers cho Features (Ví dụ: Rainfall quá cao do bão)
    # Chúng ta chỉ xử lý Outliers cho các cột đầu vào để mô hình ổn định
    feature_cols_to_fix = ['Rainfall', 'Avg Temp', 'Avg Humidity']
    
    for col in feature_cols_to_fix:
        if col in df_clean.columns:
            Q1 = df_clean[col].quantile(0.25)
            Q3 = df_clean[col].quantile(0.75)
            IQR = Q3 - Q1
            # Thay vì xóa, ta có thể "Capping" (Giới hạn) để không mất dòng
            lower_limit = Q1 - 1.5 * IQR
            upper_limit = Q3 + 1.5 * IQR
            df_clean[col] = df_clean[col].clip(lower=lower_limit, upper=upper_limit)
            
    print("Đã thực hiện Capping Outliers cho các biến thời tiết để tránh nhiễu.")
    return df_clean

# Thực thi
df = clean_features_only(df)

Đã dọn dẹp xong Logic cho các biến đầu vào. Giữ nguyên cột Production.
Đã thực hiện Capping Outliers cho các biến thời tiết để tránh nhiễu.

In [13]:
import pandas as pd
import numpy as np
from scipy.stats import skew

def handle_skewness(df):
    df_transformed = df.copy()
    
    # 1. Xác định các cột số (loại bỏ Production nếu bạn muốn giữ nguyên)
    num_cols = df_transformed.select_dtypes(include=[np.number]).columns.tolist()
    if 'Production' in num_cols:
        num_cols.remove('Production') 
    
    # 2. Tính toán độ lệch hiện tại
    skewed_feats = df_transformed[num_cols].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
    
    # 3. Lọc ra các cột có độ lệch tuyệt đối > 0.75
    high_skew = skewed_feats[abs(skewed_feats) > 0.75].index
    print(f"Các cột bị lệch nặng cần xử lý: {list(high_skew)}")
    
    # 4. Áp dụng Log Transformation (Log1p để xử lý cả giá trị 0)
    # Công thức: x' = log(1 + x)
    for col in high_skew:
        df_transformed[col] = np.log1p(df_transformed[col])
        
    print("\n--- Đã hoàn thành khử lệch bằng Log Transformation ---")
    # Kiểm tra lại độ lệch sau khi xử lý
    new_skew = df_transformed[high_skew].apply(lambda x: skew(x.dropna()))
    print("Độ lệch mới sau xử lý:")
    print(new_skew)
    
    return df_transformed

# Thực thi
df = handle_skewness(df)

Các cột bị lệch nặng cần xử lý: ['Area', 'Soil_Moisture_Season', 'LAI_Season', 'Nitrogen', 'Heat_Stress_Days', 'Organic_Carbon', 'pH', 'Clay', 'Max Relative Humidity', 'Temp_Mean', 'Min Relative Humidity']

--- Đã hoàn thành khử lệch bằng Log Transformation ---
Độ lệch mới sau xử lý:
Area                     0.617479
Soil_Moisture_Season     2.015304
LAI_Season               1.027905
Nitrogen                 1.226907
Heat_Stress_Days         0.760476
Organic_Carbon           0.874347
pH                       0.795148
Clay                     0.478580
Max Relative Humidity   -2.088379
Temp_Mean               -0.952862
Min Relative Humidity   -2.065731
dtype: float64

Chuẩn hóa đơn vị và Thang đo (Scaling)

In [14]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 4125 entries, 0 to 4534
Data columns (total 37 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Area                   4125 non-null   float64
 1   AP Ratio               4125 non-null   str
 2   District               4125 non-null   str
 3   Season                 4125 non-null   str
 4   Avg Temp               4125 non-null   float64
 5   Avg Humidity           4125 non-null   float64
 6   Crop Name              4125 non-null   str
 7   Transplant             4125 non-null   str
 8   Growth                 4125 non-null   str
 9   Harvest                4125 non-null   str
 10  Production             4125 non-null   float64
 11  Max Temp               4125 non-null   int64
 12  Min Temp               4125 non-null   float64
 13  Max Relative Humidity  4125 non-null   float64
 14  Min Relative Humidity  4125 non-null   float64
 15  NDVI_early             4125 non-null   float64
 16  NDVI_mid               4125 non-null   float64
 17  NDVI_late              4125 non-null   float64
 18  NDVI_std               4125 non-null   float64
 19  NDVI_prev_season       4125 non-null   float64
 20  EVI_Season             4125 non-null   float64
 21  LAI_Season             4125 non-null   float64
 22  FPAR_Season            4125 non-null   float64
 23  LST_Season             4125 non-null   float64
 24  Soil_Moisture_Season   4125 non-null   float64
 25  pH                     4125 non-null   float64
 26  Organic_Carbon         4125 non-null   float64
 27  Nitrogen               4125 non-null   float64
 28  Clay                   4125 non-null   float64
 29  Sand                   4125 non-null   float64
 30  Silt                   4125 non-null   float64
 31  Bulk_Density           4125 non-null   float64
 32  Rainfall               4125 non-null   float64
 33  Temp_Mean              4125 non-null   float64
 34  Temp_Max               4125 non-null   float64
 35  Temp_Min               4125 non-null   float64
 36  Heat_Stress_Days       4125 non-null   float64
dtypes: float64(29), int64(1), str(7)
memory usage: 1.2 MB

,Area,AP Ratio,District,Season,Avg Temp,Avg Humidity,Crop Name,Transplant,Growth,Harvest,...,Nitrogen,Clay,Sand,Silt,Bulk_Density,Rainfall,Temp_Mean,Temp_Max,Temp_Min,Heat_Stress_Days
0,12.085723,0.8510272331,bagerhat,kharif 2,26.0,72.5,aman,june,july to oct,nov to dec,...,1.761300,3.391820,22.08,49.20,1.23,1451.65,3.359288,33.57,18.56,0.0
1,10.152182,1.175777899,bandarban,kharif 2,26.0,72.5,aman,june,july to oct,nov to dec,...,1.095273,3.428164,38.59,31.59,1.23,1354.97,3.297642,32.68,17.05,0.0
2,12.351912,0.7705887183,barguna,kharif 2,26.0,72.5,aman,june,july to oct,nov to dec,...,1.350667,3.412137,22.40,48.27,1.26,1785.97,3.371676,32.51,20.84,0.0
3,12.620385,0.7571043893,barishal,kharif 2,26.0,72.5,aman,june,july to oct,nov to dec,...,1.305626,3.380995,25.57,46.05,1.26,1601.92,3.366993,32.47,19.53,0.0
4,12.870244,1.100652384,bhola,kharif 2,26.0,72.5,aman,june,july to oct,nov to dec,...,1.108563,3.486151,27.14,41.22,1.28,2272.77,3.382233,31.57,21.83,0.0

In [17]:
import os

# 1. Xuất ra file CSV (Khuyên dùng)
# utf-8-sig giúp hiển thị tốt tiếng Việt trong Excel
df.to_csv('Agricultural_Data_Cleaned.csv', index=False, encoding='utf-8-sig')

# 2. Xuất ra file Excel (Nếu cần)
# df_final_clean.to_excel('Agricultural_Data_Cleaned.xlsx', index=False)

print(f"✅ Đã xuất file thành công!")
print(f"📍 Vị trí file: {os.getcwd()}")
print(f"📊 Kích thước dữ liệu cuối cùng: {df.shape}")

✅ Đã xuất file thành công!
📍 Vị trí file: C:\Users\ASUS\Documents\GitHub\ADY201m-Project\baladesh data
📊 Kích thước dữ liệu cuối cùng: (4125, 37)